config/routes.rb
Bivo::Application.routes.draw do

  constraints(ShopSubdomain) do
    get "/all", :controller => "shops", :action => "index"
    get ":short_url", :controller => "shops", :action => "home", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
    get ":short_url/details", :controller => "shops", :action => "details", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
  end

  devise_for :users, :controllers => {:registrations => 'registrations' }
  match '/auth/facebook/callback' => 'facebook_authentications#create'

  #news
  post "news/:id/destroy", :to => "news#destroy"

  #gallery
  get "gallery/:entity_type/:entity_id/edit", :to => "galleries#edit", :as=>"edit_gallery"
  post "gallery/:entity_type/:entity_id/:id/move_up", :to => "galleries#move_up"
  post "gallery/:entity_type/:entity_id/:id/move_down", :to => "galleries#move_down"
  post "gallery/:entity_type/:entity_id/:id/remove_item", :to => "galleries#remove_item"
  post "gallery/:entity_type/:entity_id/add_photo", :to => "galleries#add_photo"
  post "gallery/:entity_type/:entity_id/add_video", :to => "galleries#add_video"

  #comments
  post "comments/:id/destroy", :to => "comments#destroy"
  get "comments/:id/edit", :to => "comments#edit"
  post "comments/:id/update", :to => "comments#update"
  post "comments/:id/approve", :to => "comments#approve"
  post "comments/create", :to => "comments#create"

  #incomes and expenses
  resources :expense_categories
  get "expense/list_categories", :to => "expense_categories#list_options"

  resources :income_categories
  get "income/list_categories", :to => "income_categories#list_options"

#incomes categories
  #post "income_categories/create", :to => "income_categories#create"
  #put "income_categories/update/:id", :to => "income_categories#update"
  #delete "income_categories/:id", :to => "income_categories#destroy"

  #paths for admin manager
  get "admin/send_mails"
  get "admin/tools"
  get "admin/user_manager", :as => "admin_user_manager"
  get "admin/new_personal_user", :to => "admin#new_personal_user", :as => "admin_new_personal_user"
  post "admin/create_personal_user", :to => "admin#create_personal_user", :as => "admin_create_personal_user"
  get "admin/new_charity", :to => "admin#new_charity", :as => "admin_new_charity"
  post "admin/create_charity", :to => "admin#create_charity", :as => "admin_create_charity"

  post "admin/delete_user/:id", :to => "admin#delete_user", :as => "admin_delete_user"

  get 'admin/shop/categories', :to => 'shop_categories#edit', :as => 'admin_edit_shop_categories'
  post 'admin/shop/categories/create', :to => 'shop_categories#create'
  match 'admin/shop/categories/update', :to => 'shop_categories#update'
  match 'admin/shop/categories/delete', :to => 'shop_categories#destroy'

  get 'admin/language', :to => "admin#choose_language", :as => 'translation'
  get 'admin/translate', :to => "admin#translate"

  post 'admin/save_translation', :to => "admin#save_translation"

  #paths for handling eula
  get "eula", :to => "home#eula", :as => "eula"
  get "accept_eula",  :to => "home#accept_eula", :as => "accept_eula"
  post "confirm_eula", :to => "home#confirm_eula", :as => "confirm_eula"

  #paths for dashboard
  get "dashboard", :to => "home#dashboard", :as => "dashboard"
  get "stats", :to => "home#stats", :as => "stats"

  #paths for charities
  get "charity/a/check_url", :to => "charities#check_url"

  resources :charities, :path => 'charity/a' do
    member do
      get  :manage_comments
      post :activate
      post :deactivate
      post :follow
      post :unfollow
    end
    resources :news
  end

  get "charity/:url", :controller => "charities", :action => "details", :constraints => { :url => Charity::UrlFormat }

  get "shop/a/search/", :controller => "shops", :as => "shop_search", :action => "search"

  resources :shops, :path => 'shop/a' do
    member do
      post :activate
      post :deactivate
    end
    collection do
      get :edit_categories
    end
  end

  get "cause/a/check_url", :controller => "causes", :action => "check_url", :as => 'check_cause_url'

  resources :causes, :path => 'cause/a' do
    member do
      post :activate
      post :deactivate
      post :mark_paid
      post :mark_unpaid
      post :vote
      post :follow
      post :unfollow
    end

    resources :news
  end

  get "cause/:url", :controller => "causes", :action => "details", :as => "cause_details", :constraints => { :url => Cause::UrlFormat }

  post "transaction/:id", :controller => "transactions", :action => "update",:as => "transaction_update"
  delete "transaction/:id",:controller => "transactions", :action => "destroy",:as => "transaction_destroy"
  get "transaction/:id/edit", :controller => "transactions", :action => "edit", :as => "transaction_edit"

  get "transaction", :controller => "transactions", :action => "index", :as => 'transaction_list'

  resources :transactions, :path => 'transaction', :except => :destroy

  post "change_language", :to => "home#change_language"
  post "change_currency", :to => "home#change_currency"

  # path for static pages
  get "about(/:id)", :to => "home#about"
  get "about/:locale/:id", :to => "home#about"

  root :to => "home#index"

end

app/views/admin/_users.html.erb
<table class="zebra_table">
  <tr>
    <th style="width:278px;">
      <%= link_to _("Name"), request.parameters.merge({:sort_by => get_sort_for("name")}) %> 
    </th>
    <th style="width:90px;">
      <%= link_to _("Type"), request.parameters.merge({:sort_by => get_sort_for("type")}) %>
    </th>
    <th style="width:140px;">
      <%= link_to _("Last Login"), request.parameters.merge({:sort_by => get_sort_for("last_sign_in_at")}) %>
    </th>
    <th style="width:140px;">
      <%= link_to _("Signup Date"), request.parameters.merge({:sort_by => get_sort_for("created_at")}) %>
    </th>
    <th style="width:130px;">&nbsp;</th>
    <th style="width:75px;">&nbsp;</th>
    <th class="noBord" style="width:90px;">&nbsp;</th>
  </tr>
  <% for user in @users %>
    <tr>
      <% if user.is_charity_user -%>
      <td class ="username"><%= link_to user.name, url_charity(user) %></td>
      <% else -%>
      <td class ="username"><%= user.name %></td>
      <% end -%>
      <td><%= user.type %></td>
      <td><%= format_date user.last_sign_in_at %></td>
      <td><%= format_date user.created_at %></td>
      <td id="activate_deactivate_charity_btn_<%=user.id%>"><%= active_deactive_charity_button(user) if user.is_charity_user %></td>
      <td><%= orange_link_to _("Edit"), edit_user_registration_path(:id => user.id) %></td>
      <td class="noBord"><%= orange_link_to _("Delete"), { :action => "destroy", :controller => "registrations", :id => user.id }, :confirm => "are you sure you want to delete the user?", :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/admin/add_income_and_expense.html.erb
<h2>
  <%= _("Add Income/Expense") %>
</h2>

<% content_for :js do %>

$(document).ready(function(){
  $("a.iframe").fancybox({
    'onClosed': function() {

		  // save current selection
		  var current_selection = $('#transaction_expense_category_id').val();

		  $('#transaction_expense_category_id')
		  .load('<%=url_for :controller => 'expense_categories', :action => 'list_options'%>', function(){
        if (current_selection) {
          $("#transaction_expense_category_id option[value='" + current_selection + "']").attr('selected', 'selected');
        }
		  });
    }
  });

  $('#transaction_income_category_id').change(function() {
    var selectedCategory = $('#transaction_income_category_id :selected').text();
    if (selectedCategory == "shop") {
      $("#shop").css("display", "block");
    } else {
      $("#shop").css("display", "none");
    }
  });

  $('#transaction_type').change(function() {
    var selectedCategory = $('#transaction_type :selected').text();
    if (selectedCategory == "Income") {
      $("#income_fields").css("display", "block");
      $("#expense_fields").css("display", "none");
    } else if (selectedCategory == "Expense") {
      $("#income_fields").css("display", "none");
      $("#expense_fields").css("display", "block");
    } else {
      $("#income_fields").css("display", "none");
      $("#expense_fields").css("display", "none");
    }
  });

  $('#cancel').click(function () {
    location.href = "<%= root_path %>";
    return false;
  })
});

<% end %>

<%= form_for(@transaction, :as => :transaction, :url => create_income_and_expense_path) do |f| %>
  <%= render "shared/error_messages", :target => @transaction %>

  <p><%= f.label :type %><br />
  <%= f.select :type, [["Income","Income"], ["Expense","Expense"]], :include_blank => true %></p>

  <p><%= f.label :date %><br />
  <%= f.date_select :transaction_date %></p>

  <div id="income_fields" style="<%= get_display_of :Income, @transaction %>">
    <%= render :partial => "income_fields",
          :locals => {:f => f, :income_categories => @income_categories, :shops => @shops, :transaction => @transaction} %>
  </div>

  <div id="expense_fields" style="<%= get_display_of :Expense, @transaction %>">
    <%= render :partial => "expense_fields",
          :locals => {:f => f, :expense_categories => @expense_categories} %>
  </div>

  <p><%= f.label :amount %><br />
  <%= select_tag :currency, options_for_select(@currencies, @currency) %>
  <%= f.text_field :amount %></p>

  <p><%= f.label :description %><br />
  <%= f.text_area :description %></p>

  <p><%= f.submit :Save %> <%= f.submit :Cancel, :id => "cancel" %></p>
<% end %>

app/views/admin/choose_language.html.erb
<%= large_single_block _("Choose a language for start translations") do %>
<div class="default_font">
<% @languages.each do |lang|%>
	<%= link_to "#{lang.name} (#{Shop.translation_pending(lang.id).count} pending translations)", :action => "translate", :language_for_transalte => lang.id%> <br/>
<% end %>
</div>

<br class="spacer" />
<%=back_button(_("Go back"))%>
<br class="spacer" />

<% end %>

app/views/admin/index.html.erb
<%= link_to "Add User", admin_new_personal_user_path %> |
<%= link_to "Add Charity", admin_new_charity_path %>

<br /><br />
<%= form_tag admin_user_manager_path, :method => "get" do %>
<div>
<%= _("Show") %> <%= select_tag :show, options_for_select(@show_options) %> <br />
<%= _("Size per page")%> <%= select_tag :per_page, options_from_collection_for_select(@page_sizes, 'to_i', 'to_s', @per_page)%> <br />
<%= _("Filter by") %> <%= text_field_tag :filter, @filter %> <br />
<br />
<%= submit_tag("Search") %>
</div>
<% end %>
<br />
<div id="results">
  <%= will_paginate @users %>
  <table>
    <tr>
      <th>&nbsp;</th>
      <th><%= link_to _("Name"), request.parameters.merge({:sort_by => get_sort_for("name")}) %></th>
      <th><%= link_to _("Type"), request.parameters.merge({:sort_by => get_sort_for("type")}) %></th>
      <th><%= link_to _("Status"), request.parameters.merge({:sort_by => get_sort_for("status")}) %></th>
      <th><%= link_to _("Last Login"), request.parameters.merge({:sort_by => get_sort_for("last_sign_in_at")}) %></th>
      <th><%= link_to _("Signup Date"), request.parameters.merge({:sort_by => get_sort_for("created_at")}) %></th>
      <th>&nbsp;</th>
    </tr>
  <% for user in @users %>
    <tr>
      <td><%= link_to _("Delete"), admin_delete_user_path(user.id), :confirm => "are you sure you want to delete the user?", :method => :post %></td>
      <td><%= user.name %></td>
      <td><%= user.type %></td>
      <td><%= user.status %></td>
      <td><%= format_date user.last_sign_in_at %></td>
      <td><%= format_date user.created_at %></td>
      <td><%= link_to _("Edit"), admin_edit_user_path(user.id) %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/admin/new_charity.html.erb
<%= single_block _("Create New Charity") do %>
<%= bivo_form_for(@resource, :as => @resource_name, :url => admin_create_charity_path) do |f| %>
  <%= render "shared/error_messages", :target => @resource %>

  <%= hidden_field_tag :referer, @referer %>

  <%= f.label :email, _("E-Mail") %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :charity_name, "Charity Name" %>
  <%= f.text_field :charity_name %>

  <%= f.label :charity_website, "Charity Website" %>
  <%= f.text_field :charity_website %>

  <%= f.label _("Short Url")%>
  <p style ="display:inline;" >
    <span><%= charity_short_url_prefix %></span>
    <%= f.inline_text_field :short_url, :id => 'short_url', :onfocus => "javascript:$('#available').html('');", :style => "width: 158px; float:none; padding-left:7px;"%>
	<%= inline_orange_link_to _('Check Url'), "#", { :onclick => "javascript:checkUrl(); return false;"} %>
  </p>
  <br class="accfilTxt" />
  <p style="font: normal normal normal 13px/24px Arial, Helvetica, sans-serif; margin-left: 175px"><span id="available"></span></p>
  <br/>

  <%= f.label :category, "Category" %>
  <%= f.select :charity_category_id, @categories.collect{ |c| [c.name, c.id] }, :include_blank => true %>

  <%= f.label :charity_type, "Charity Type" %>
  <%= f.text_field :charity_type %>

  <%= f.label :tax_reg_number, "Tax Registration Number" %>
  <%= f.text_field :tax_reg_number %>

  <%= f.label :rating, "Rating" %>
  <%= select 'charity', 'rating', @ratings, {:include_blank => true},{ :class => "accChoo accfil" }%>
  <br class="spacer" />

  <%= f.label :country, "Country" %>
  <%= f.select :country_id, @countries.collect{ |c| [c.name, c.id] }, :include_blank => true %>

  <%= f.label :city, "City" %>
  <%= f.text_field :city %>

  <%= f.label _("Description") %>
  <%= f.wysiwyg :description %>

  <% content_for :js do %> <!-- javascript code to run, for this view only -->
    <%= render :partial => 'shared/check_url', :locals => {
      :is_new => true, :url_was => nil, :url_check => '/charity/a/check_url'
    } %>
  <%end%>

  <div class="buttons">
  	<%= f.submit _("Create Account") %>
    <%= back_button (_("Cancel"))%>
  </div>
<% end %>
<% end %>

app/views/admin/new_personal_user.html.erb
<%= single_block _("Create Personal User") do %>
<%= bivo_form_for(@resource, :as => @resource_name, :url => admin_create_personal_user_path) do |f| %>
  <%= render "shared/error_messages", :target => @resource %>

  <%= hidden_field_tag :referer, @referer %>

  <%= f.label :email, _("E-Mail") %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name %>

  <%= f.label :nickname, "Nickname (optional)" %>
  <%= f.text_field :nickname %>

  <%= f.label :birthday, "Birthday" %>
  <%= f.date_select :birthday, {:prompt => {:day => _('Choose day'), :month => _('Choose month')}, :discard_year => true}, :class =>"accfil accChoo", :style => "width: 181px !important;" %>
  <br class="spacer"/>

  <%= f.label :gender, "Sex (optional)" %>
  <%= f.select :gender, [["Male","M"], ["Female","F"]], :include_blank => true %>

  <div class="buttons">
    <%= f.submit _("Create Account") %>
    <%= back_button (_("Cancel"))%>
  </div>
<% end %>
<% end %>

app/views/admin/tools.html.erb
<div class="inbodyM">
	<div class="bodyInner">

<div class="bodyInL">
	<div class="bodyInLTop"><span></span></div>
	<div class="bodyInLmid">
		<div class="bodyInLmidIn">
			<h2>Main</h2>
			<ul>
				<li><%= link_to _("User manager"), admin_user_manager_path %> </li>
				<li><%= link_to _("Shops"), all_shops_path %></li>
				<li><%= link_to _("Charities"), charities_path %></li>
			</ul>
			<h2>Accounting</h2>
			<ul>
				<li><%= link_to _("Transaction manager"), transaction_list_path %></li>
				<li><%= link_to _("Stats"), stats_path %></li>
				<li><%= link_to _("Dashboard"), dashboard_path %> </li>				
			</ul>
			<h2>Site Maintenance</h2>
			<ul>
				<li><%= link_to "Run processor", :action => 'send_mails' %></li>
				<li><%= link_to _("Translation manager"), translation_path %> </li>				
			</ul>
         </div>
    </div>
	<div class="bodyInLbot"></div>
</div>

<div class="bodyInR">
	<h2><%= _("Admin tools") %></h2>
	
	<div class="bodyInRBox"><div class="bodyInRBox2">
		<p class="InneRTxt">There are <%= @pending_mails %> pending mails. <%= link_to "Run processor", :action => 'send_mails' %></p>
	</div></div>
</div>

	</div>
</div>

app/views/admin/translate.html.erb
<%= large_single_block _("Translations for %s") % Language.by_id(@t_language).name do %>

<% @translated_classes.each do |clazz|%>
	<%clazz.translated_fields[:translate].each do |field|%>
	
	<div class="cvNews"><h2><%= clazz.name%> <%=field.to_s%></h2></div>
	<div class="cvNewsBox"><div style="padding: 20px;">
	
			<ul>
				<% clazz.translation_pending(@t_language).each do |instance|%>
					<%= form_tag({:action => "save_translation", :id => instance.id, :clazz => clazz.name, :t_field => field, :lang => @t_language}, {:remote => true}) do %>
						<li>
							<p class="accfilTxt">
								<%= label_tag :translation, instance.send(field)%>
							</p>
						    <%= text_field_tag :translation, nil, :class => "accfil", :style => "margin-right: 10px" %>
						    <%= orange_submit_tag "Translate" %>
							<br class="spacer"/>
						</li>
					  <% end %>		
				<%end%>
			</ul>

			<br class="spacer" />
			<%=back_button(_("Go back"))%>
			<br class="spacer" />
	</div></div>
	
	<%end%>
		
<%end%>

<%end%>

app/views/admin/user_manager.html.erb
<%= large_single_block _('User manager') do %>
  <br class="spacer" />
	<%= orange_link_to _("Add User"), admin_new_personal_user_path %>
	<%= orange_link_to _("Add Charity"), admin_new_charity_path %>
	<br /><br />
	<%= form_tag admin_user_manager_path, :method => "get" do %>
	  <div class="gnFilMain2">
	    <p class="genFilTxt2"><%= _("Show") %> <%= select_tag :show, options_for_select(@show_options, @show), :class => :genChoo2 %></p>
	    <p class="genFilTxt2">Filter by</p><%= text_field_tag :filter, @filter, :class => "genFil" %></p>
      <div><%= orange_button_to _("Search"), :disable_with => _('Searching...') %></div>
      <%= styled_will_paginate @users %>
    </div>
  <% end %>
    <br class="spacer" />
    <%= render 'users' %>
    <%= form_tag admin_user_manager_path, :method => "get" do %>
      <%= hidden_field_tag :show, @show %>
      <%= hidden_field_tag :filter, @filter %>
      <br class="spacer" />
	    <%= select_tag :per_page, options_from_collection_for_select(@page_sizes, 'to_i', 'to_s', @per_page), :class => :showChoo, :onchange => submit_form %>
      <p class="showTxt"><%= _("Show per page")%></p>
      <br />
    <% end %>
    </table>
<% end %>