config/routes.rb
Bivo::Application.routes.draw do

  constraints(ShopSubdomain) do
    get "/all", :controller => "shops", :action => "index"
    get ":short_url", :controller => "shops", :action => "home", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
    get ":short_url/details", :controller => "shops", :action => "details", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
  end

  devise_for :users, :controllers => {:registrations => 'registrations' }
  match '/auth/facebook/callback' => 'facebook_authentications#create'

  #news
  post "news/:id/destroy", :to => "news#destroy"

  #gallery
  get "gallery/:entity_type/:entity_id/edit", :to => "galleries#edit", :as=>"edit_gallery"
  post "gallery/:entity_type/:entity_id/:id/move_up", :to => "galleries#move_up"
  post "gallery/:entity_type/:entity_id/:id/move_down", :to => "galleries#move_down"
  post "gallery/:entity_type/:entity_id/:id/remove_item", :to => "galleries#remove_item"
  post "gallery/:entity_type/:entity_id/add_photo", :to => "galleries#add_photo"
  post "gallery/:entity_type/:entity_id/add_video", :to => "galleries#add_video"

  #comments
  post "comments/:id/destroy", :to => "comments#destroy"
  get "comments/:id/edit", :to => "comments#edit"
  post "comments/:id/update", :to => "comments#update"
  post "comments/:id/approve", :to => "comments#approve"
  post "comments/create", :to => "comments#create"

  #incomes and expenses
  resources :expense_categories
  get "expense/list_categories", :to => "expense_categories#list_options"

  resources :income_categories
  get "income/list_categories", :to => "income_categories#list_options"

#incomes categories
  #post "income_categories/create", :to => "income_categories#create"
  #put "income_categories/update/:id", :to => "income_categories#update"
  #delete "income_categories/:id", :to => "income_categories#destroy"

  #paths for admin manager
  get "admin/send_mails"
  get "admin/tools"
  get "admin/user_manager", :as => "admin_user_manager"
  get "admin/new_personal_user", :to => "admin#new_personal_user", :as => "admin_new_personal_user"
  post "admin/create_personal_user", :to => "admin#create_personal_user", :as => "admin_create_personal_user"
  get "admin/new_charity", :to => "admin#new_charity", :as => "admin_new_charity"
  post "admin/create_charity", :to => "admin#create_charity", :as => "admin_create_charity"

  post "admin/delete_user/:id", :to => "admin#delete_user", :as => "admin_delete_user"

  get 'admin/shop/categories', :to => 'shop_categories#edit', :as => 'admin_edit_shop_categories'
  post 'admin/shop/categories/create', :to => 'shop_categories#create'
  match 'admin/shop/categories/update', :to => 'shop_categories#update'
  match 'admin/shop/categories/delete', :to => 'shop_categories#destroy'

  get 'admin/language', :to => "admin#choose_language", :as => 'translation'
  get 'admin/translate', :to => "admin#translate"

  post 'admin/save_translation', :to => "admin#save_translation"

  #paths for handling eula
  get "eula", :to => "home#eula", :as => "eula"
  get "accept_eula",  :to => "home#accept_eula", :as => "accept_eula"
  post "confirm_eula", :to => "home#confirm_eula", :as => "confirm_eula"

  #paths for dashboard
  get "dashboard", :to => "home#dashboard", :as => "dashboard"
  get "stats", :to => "home#stats", :as => "stats"

  #paths for charities
  get "charity/a/check_url", :to => "charities#check_url"

  resources :charities, :path => 'charity/a' do
    member do
      get  :manage_comments
      post :activate
      post :deactivate
      post :follow
      post :unfollow
    end
    resources :news
  end

  get "charity/:url", :controller => "charities", :action => "details", :constraints => { :url => Charity::UrlFormat }

  get "shop/a/search/", :controller => "shops", :as => "shop_search", :action => "search"

  resources :shops, :path => 'shop/a' do
    member do
      post :activate
      post :deactivate
    end
    collection do
      get :edit_categories
    end
  end

  get "cause/a/check_url", :controller => "causes", :action => "check_url", :as => 'check_cause_url'

  resources :causes, :path => 'cause/a' do
    member do
      post :activate
      post :deactivate
      post :mark_paid
      post :mark_unpaid
      post :vote
      post :follow
      post :unfollow
    end

    resources :news
  end

  get "cause/:url", :controller => "causes", :action => "details", :as => "cause_details", :constraints => { :url => Cause::UrlFormat }

  post "transaction/:id", :controller => "transactions", :action => "update",:as => "transaction_update"
  delete "transaction/:id",:controller => "transactions", :action => "destroy",:as => "transaction_destroy"
  get "transaction/:id/edit", :controller => "transactions", :action => "edit", :as => "transaction_edit"

  get "transaction", :controller => "transactions", :action => "index", :as => 'transaction_list'

  resources :transactions, :path => 'transaction', :except => :destroy

  post "change_language", :to => "home#change_language"
  post "change_currency", :to => "home#change_currency"

  # path for static pages
  get "about(/:id)", :to => "home#about"
  get "about/:locale/:id", :to => "home#about"

  root :to => "home#index"

end

app/views/shared/_check_url.html.erb
function checkUrl() {
  <% unless is_new %>
	  if('<%= url_was %>' == $("#short_url").val()) {
		  showAvailable(true);
		  return;
	  }
  <% end %>
  $("#available").html('<%=_("checking...")%>');
  $("#checkBtn").attr('disabled','disabled');
  $.ajax({
	  url: "<%= url_check %>",
	  data: {url : $("#short_url").val()},
	  success: function(status) {
		  $("#checkBtn").removeAttr('disabled');
		  showAvailable(status);
	  }
  });
}

function showAvailable(urlStatus) {
  if (urlStatus == "available") {
    $("#available").html('<%=_("Available")%>');
  } else if (urlStatus == "not_available") {
    $("#available").html('<%=_("Unavailable")%>');
  } else if (urlStatus == "invalid") {
    $("#available").html('<%=_("Invalid Format")%>');
  }
}

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
	<div class="error">
    <p><%= _('The following errors have occurred:')%></p>
		<ul>
			<% target.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="infootM">
  <div class="infootIn">
    <ul>
      <li>
        <strong><%=_("About Bivo")%></strong>	
        <%= link_to _("Who We Are?"), static_page(:who_we_are) %>
        <%= link_to _("How Does it Work?"), static_page(:how_it_works) %>
        <%= link_to _("FAQ"), static_page(:faq) %>
        <%= link_to _("Our Team"), static_page(:our_team) %>
        <%= link_to _("Charities We Help"), charities_url %>
		<%= link_to _("Shops"), all_shops_path %>
        <%= link_to _("Statistics"), stats_url %>
        <%= link_to _("Contact Us"), static_page(:contact_us) %>
      </li>
      <li>
        <strong><%=_("Bivo Ideas")%></strong>
        <%= link_to _("Fund Raisers"), static_page(:fund_raisers) %>
        <%= link_to _("Social Initiatives"), static_page(:social_initiatives) %>
      </li>
      <li>
        <strong><%=_("Help Bivo")%></strong>
        <%= link_to _("Spread the Word"), static_page(:spread_the_word) %>
        <%= link_to _("Volunteer"), static_page(:volunteer) %>
        <%= link_to _("Send Feedback"), feedback_url %>
      </li>
      <li>
        <strong><%=_("International")%></strong><%@languages.each do |l| %>
        <a href="#" onclick="$('#language').val('<%=l.id%>'); $('#language').change(); return false;"><%=l.name%></a><%end%>
      </li>
<!--<%= link_to _("Shops"), shops_url %>-->
      <li class="infootcopyM noBg">
        <span class="infootcopy">
          &copy; <%=_("2010 Bivo. All Rights Reserved.")%>
          <br />
          <%=_("Bivo is a Community Interest Company")%>
          <br />
          <%=_("Registered in England")%>
        </span>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_notifications.js.erb
<% [:notice, :alert, :error].each do |kind| %>
  <% if flash[kind]%>
	  $.jGrowl("<%= flash[kind] %>", <%= options_for_javascript(flash["#{kind.to_s}_options".intern] || {}) %>);
  <% end %>
<% end %>

app/views/shared/_pre_footer.html.erb
<div class="bodyM">
	<div class="bodyIn">
      <div class="bodyDIVI">
            <div class="bodyL">
                <h2 class="bodyHead <%=if @section == :home_index then 'bodyHead2' end%>"><%=_("Choose Your Cause")%></h2>
                <p class="bodytxt <%=if @section == :home_index then 'bodytxt2' end%>"><%=_("Vote for charitable causes from around the globe.")%></p>
                <p class="bodytxt <%=if @section == :home_index then 'bodytxt2' end%>"><%=_("Causes with the most votes get funds faster.")%></p>
                <%= link_to _("Vote Causes"), causes_url, :class=>"bodyLBtn"  %>
            </div>
            <div class="bodyMid">
                <h2 class="bodyHead <%=if @section == :home_index then 'bodyHead2' end%>"><%=_("Change the World")%></h2>
                <p class="bodytxt <%=if @section == :home_index then 'bodytxt2' end%>"><%=_("Bivo donates commissions from all sales to the causes our users choose.")%></p>
                <p class="bodytxt <%=if @section == :home_index then 'bodytxt2' end%>"><%=_("To see how your contribution is distributed, check out Bivo's fundraising dashboard.")%></p>

                <%= link_to _("Go to Dashboard"), dashboard_url,:class=>"bodyLBtn bodyMidBtn" %>
            </div>
            <div class="bodyR">
                <h2 class="bodyHead <%=if @section == :home_index then 'bodyHead2' end%>"><%=_("Spread the Word")%></h2>
                <p class="bodytxtR <%=if @section == :home_index then 'bodytxtR2' end%>"><%=_("Tell your friends about Bivo and get even more funding for your favorite causes..")%></p>

                <h2 class="bodyHead <%=if @section == :home_index then 'bodyHead2' end%>"><%=_("Volunteer")%></h2>
                <p class="bodytxtR <%=if @section == :home_index then 'bodytxtR2' end%>"><%= raw(_("%s at Bivo and help us -- and the charities we support -- grow.") % link_to(_("Volunteer your time"), static_page(:volunteer))) %></p>

                <h2 class="bodyHead <%=if @section == :home_index then 'bodyHead2' end%>"><%=_("Support other Fundraisers")%></h2>
                <p class="bodytxtR <%=if @section == :home_index then 'bodytxtR2' end%> noMarg"><%= raw(_("Learn more about Bivo's other %s and %s.") % [link_to(_("social initiatives"), static_page(:social_initiatives)), link_to(_("fund raising projects"), static_page(:fund_raisers))]) %></p>
            </div><br class="spacer" />
      </div>
  </div>
  <div class="bodyBot"></div>
</div>

app/views/shared/_user_nav.html.erb
<% content_for(:js) do %>
  $(function() {
    $('#language').change(function() {
      $('#nav_form').submit();
    });
	});
<% end %>

<% if @section == :home_index || @section == :shop_home %>
	<div class="headerFull">
<%else%>
	<div class="innheaderFull">
<%end%>
	  <div class="main">
		<%= link_to image_tag("logo.png", :size => "211x77", :alt => "Bivo", :title => "Bivo"), root_url %>
	    <div class="topDropDev default_font">
	      <% if user_signed_in? %>
          		<%= _("Signed in as") %> <%= current_user.from_facebook ? current_user.facebook_email : current_user.email %> - 
	          <% if (current_user.type == "Charity") %>
	            <%= link_to _("My Home"), url_charity(current_user) %> - 
	            <%= link_to _("Settings"), edit_user_registration_url %>
	          <% elsif (current_user.type == "PersonalUser") %>
	            <%= link_to _("Settings"), edit_user_registration_url %>
	          <% elsif (current_user.type == "Admin") %>
	            <%= link_to _("Admin Tools"), admin_tools_url %>
	          <% end %>
	      <% end %>		
		    <%= form_tag(change_language_url, :method => "post", :id => "nav_form", :class => "inline") do %>
	      	<%= select_tag :language, options_for_select(languages.collect { |l| [l.name, l.id] }, language.id ), :onchange => submit_parent_form %>
		    <% end %>
		    <%= form_tag(change_currency_url, :method => "post", :id => "curr_form", :class => "inline") do %>
	      	<%= select_tag :currency, options_for_select(all_currencies.collect { |c| [c.name, c.id] }, current_currency.id), :onchange => submit_parent_form %>
		    <% end %>
	    </div><br class="spacer" />
	    <ul class="nav">
		    <li><%= link_to _("Home"), root_url, :class => if @section == :home_index then "selected" end %></li><li class="navPipe"><%= image_tag "navPipe.png", :size => "2x19"%></li>
		    <li><%= link_to _("Vote Causes"), causes_url, :class => if @section == :vote_causes then "selected" end %></li><li class="navPipe"><%= image_tag "navPipe.png", :size => "2x19"%></li>
		    <li><%= link_to _("Dashboard"), dashboard_url, :class => if @section == :dashboard then "selected" end %><li class="navPipe"><%= image_tag "navPipe.png", :size => "2x19"%></li>
		    <li><%= link_to _("About Bivo"), static_page(:who_we_are), :class => if @section == :about then "selected" end %><li class="navPipe"><%= image_tag "navPipe.png", :size => "2x19"%></li>
	      <% if user_signed_in? %>
	        <li><%= link_to _("Logout"), destroy_user_session_url %></li><br class="spacer" />
	      <% else %>
		    <li><%= link_to _("Login"), new_user_session_url, :class => if @section == :login then "selected" end %></li><br class="spacer" />
	      <% end %>
	    </ul>
	  <%if @section == :home_index || @section == :shop_home %>
        <%= content_for :home_content %>
	  <%end%>
	  </div>
<% if @section == :home_index || @section == :shop_home %>	
	  <div class="headerFullIn"></div>
<% end %>
	</div>

app/views/shared/inactive.html.erb
<h2>
  <p id="page_inactive"><%=_('The')%> <%=@kind%> <%=@name%> <%=_('is inactive.')%></p>
  <p id="doubts_contact"><%=_('For any doubts, please contact')%> <a href="info@bivo.org" >info@bivo.org</a></p>
</h2>