config/routes.rb
Bivo::Application.routes.draw do

  constraints(ShopSubdomain) do
    get "/all", :controller => "shops", :action => "index"
    get ":short_url", :controller => "shops", :action => "home", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
    get ":short_url/details", :controller => "shops", :action => "details", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
  end

  devise_for :users, :controllers => {:registrations => 'registrations' }
  match '/auth/facebook/callback' => 'facebook_authentications#create'

  #news
  post "news/:id/destroy", :to => "news#destroy"

  #gallery
  get "gallery/:entity_type/:entity_id/edit", :to => "galleries#edit", :as=>"edit_gallery"
  post "gallery/:entity_type/:entity_id/:id/move_up", :to => "galleries#move_up"
  post "gallery/:entity_type/:entity_id/:id/move_down", :to => "galleries#move_down"
  post "gallery/:entity_type/:entity_id/:id/remove_item", :to => "galleries#remove_item"
  post "gallery/:entity_type/:entity_id/add_photo", :to => "galleries#add_photo"
  post "gallery/:entity_type/:entity_id/add_video", :to => "galleries#add_video"

  #comments
  post "comments/:id/destroy", :to => "comments#destroy"
  get "comments/:id/edit", :to => "comments#edit"
  post "comments/:id/update", :to => "comments#update"
  post "comments/:id/approve", :to => "comments#approve"
  post "comments/create", :to => "comments#create"

  #incomes and expenses
  resources :expense_categories
  get "expense/list_categories", :to => "expense_categories#list_options"

  resources :income_categories
  get "income/list_categories", :to => "income_categories#list_options"

#incomes categories
  #post "income_categories/create", :to => "income_categories#create"
  #put "income_categories/update/:id", :to => "income_categories#update"
  #delete "income_categories/:id", :to => "income_categories#destroy"

  #paths for admin manager
  get "admin/send_mails"
  get "admin/tools"
  get "admin/user_manager", :as => "admin_user_manager"
  get "admin/new_personal_user", :to => "admin#new_personal_user", :as => "admin_new_personal_user"
  post "admin/create_personal_user", :to => "admin#create_personal_user", :as => "admin_create_personal_user"
  get "admin/new_charity", :to => "admin#new_charity", :as => "admin_new_charity"
  post "admin/create_charity", :to => "admin#create_charity", :as => "admin_create_charity"

  post "admin/delete_user/:id", :to => "admin#delete_user", :as => "admin_delete_user"

  get 'admin/shop/categories', :to => 'shop_categories#edit', :as => 'admin_edit_shop_categories'
  post 'admin/shop/categories/create', :to => 'shop_categories#create'
  match 'admin/shop/categories/update', :to => 'shop_categories#update'
  match 'admin/shop/categories/delete', :to => 'shop_categories#destroy'

  get 'admin/language', :to => "admin#choose_language", :as => 'translation'
  get 'admin/translate', :to => "admin#translate"

  post 'admin/save_translation', :to => "admin#save_translation"

  #paths for handling eula
  get "eula", :to => "home#eula", :as => "eula"
  get "accept_eula",  :to => "home#accept_eula", :as => "accept_eula"
  post "confirm_eula", :to => "home#confirm_eula", :as => "confirm_eula"

  #paths for dashboard
  get "dashboard", :to => "home#dashboard", :as => "dashboard"
  get "stats", :to => "home#stats", :as => "stats"

  #paths for charities
  get "charity/a/check_url", :to => "charities#check_url"

  resources :charities, :path => 'charity/a' do
    member do
      get  :manage_comments
      post :activate
      post :deactivate
      post :follow
      post :unfollow
    end
    resources :news
  end

  get "charity/:url", :controller => "charities", :action => "details", :constraints => { :url => Charity::UrlFormat }

  get "shop/a/search/", :controller => "shops", :as => "shop_search", :action => "search"

  resources :shops, :path => 'shop/a' do
    member do
      post :activate
      post :deactivate
    end
    collection do
      get :edit_categories
    end
  end

  get "cause/a/check_url", :controller => "causes", :action => "check_url", :as => 'check_cause_url'

  resources :causes, :path => 'cause/a' do
    member do
      post :activate
      post :deactivate
      post :mark_paid
      post :mark_unpaid
      post :vote
      post :follow
      post :unfollow
    end

    resources :news
  end

  get "cause/:url", :controller => "causes", :action => "details", :as => "cause_details", :constraints => { :url => Cause::UrlFormat }

  post "transaction/:id", :controller => "transactions", :action => "update",:as => "transaction_update"
  delete "transaction/:id",:controller => "transactions", :action => "destroy",:as => "transaction_destroy"
  get "transaction/:id/edit", :controller => "transactions", :action => "edit", :as => "transaction_edit"

  get "transaction", :controller => "transactions", :action => "index", :as => 'transaction_list'

  resources :transactions, :path => 'transaction', :except => :destroy

  post "change_language", :to => "home#change_language"
  post "change_currency", :to => "home#change_currency"

  # path for static pages
  get "about(/:id)", :to => "home#about"
  get "about/:locale/:id", :to => "home#about"

  root :to => "home#index"

end

app/controllers/home_controller.rb
require 'money'
require 'money/bank/google_currency'

class HomeController < ApplicationController
  MIN_FONT_TAG_CLOUD = 15  
  MAX_FONT_TAG_CLOUD = 40  
  skip_before_filter :set_gettext_locale, :only => [:change_language]
  skip_before_filter :check_eula_accepted, :only => [:accept_eula, :confirm_eula]

  def index
    @section = :home_index
    @raised_amount = Income.funds_raised(1.month.ago, Date.today)
  end

  def eula

  end

  def accept_eula
    unless (user_signed_in? && !current_user.eula_accepted)
      redirect_to root_path
    end
  end

  def confirm_eula
    if (params[:eula_accepted])
      current_user.eula_accepted = true
      current_user.save
    end

    redirect_to root_path
  end

  def dashboard
    @section = :dashboard
    load_periods
    
    @funds_raised = Income.funds_raised(@from, @to)
    @transactions = Income.transactions_count(@from, @to)
    @causes_raising_funds = Cause.where(:status => :raising_funds).all
    @causes_being_funded = Cause.causes_being_funded(@from, @to)
    @most_voted_causes = Cause.most_voted_causes(@from, @to)
    @fully_funded_causes = Cause.fully_funded(@from, @to).count
    @shops_to_cloud = get_shops_with_font_calculation(Shop.all, @from, @to)
  end
  
  def stats
    load_periods

    @cash_reserves = Account.cash_reserves_account.balance_at(@to)

    @expenses = Expense.between(@from, @to)
    @expense_categories = ExpenseCategory.stats(@from, @to)
    @expenses_total = @expense_categories.sum(&:amount) rescue 0.to_d

    @revenues = Income.between(@from, @to)
    @revenue_categories = IncomeCategory.stats(@from, @to)
    @revenues_total = @revenue_categories.sum(&:revenue_amount) rescue 0.to_d
  end

  def change_language
    if ((params["language"]) && (Language.all.map(&:id).include? params["language"].to_sym))
      session[:locale] = params["language"].to_sym
    end

    if (user_signed_in?)
      current_user.preferred_language = session[:locale]
      current_user.save
    end

    redirect_to request.referrer
  end

  def change_currency
    if params[:currency] && Currency.by_id(params[:currency])
      session[:currency] = params[:currency].to_sym
    end

    if (user_signed_in?)
      current_user.preferred_currency = session[:currency]
      current_user.save
    end

    redirect_to request.referrer
  end

  def about
    @section = :about
    @id = params[:id].try(:to_sym) || :who_we_are
    if !params[:locale].blank?
      session[:locale] = params[:locale].to_sym
      I18n.locale = params[:locale].to_sym
    end
  end
  
  protected

  def get_shops_with_font_calculation(shops_to_cloud, from, to)
    shops_to_cloud.each do |shop| 
      shop.define_accessor :incomes_sum, shop.incomes_in_period(from, to)
    end
    
    shops_to_cloud = shops_to_cloud.select { |shop| shop.incomes_sum.round.to_i > 0 }
    # calculation to map minimum and maximum incomes to the minimum and maximum fonts in shop cloud.
    period_incomes = shops_to_cloud.map { |shop| shop.incomes_sum }    
    min_found = period_incomes.min || 0
    max_found = period_incomes.max || 0
    min_font = MIN_FONT_TAG_CLOUD.to_d
    max_font = MAX_FONT_TAG_CLOUD.to_d

    pend = ((max_font - min_font) / (max_found - min_found))
    offset = max_font - (pend * max_found)

    shops_to_cloud.each do |shop|
      if (min_found == max_found)
        shop.define_accessor :font_size, (min_font + max_font) / 2.0
      else
        shop.define_accessor :font_size, ((pend * shop.incomes_sum) + offset).round
      end
    end

    shops_to_cloud
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def link_to_static_page(id)
    if @id == id
      html = { :class => 'leftSelect' }
    else
      html = {}
    end
    
    link_to static_page_title(id), static_page(id), html
  end
  
  def static_page_title(id)
    case id
      when :who_we_are         then _("Who we are?")
      when :how_it_works       then _("How Does it Work?")
      when :faq                then _("FAQ")
      when :our_team           then _("Our team")
      when :contact_us         then _("Contact Us")

      when :fund_raisers       then _("Fund Raisers")
      when :social_initiatives then _("Social Initiatives")

      when :spread_the_word    then _("Spread the Word")
      when :volunteer          then _("Volunteer")
    end
  end
end

app/views/home/_cause_card.html.erb
<%
	loader_width = (138 * cause.funds_raised/cause.funds_needed).to_i
%>
<div class="boxHu">
	<h3><%= cause.cause_category.name %></h3>
   <p class="boxHuTxt"><%= link_to_cause cause %></p>
   <div class="loadMain">
     <img src="images/loader-green.jpg" width="<%= loader_width %>" height="20" alt="" class="load" style="float: left;" />
     <img src="images/loader-gray.jpg" width="<%= 138 - loader_width %>" height="20" alt="" class="load" />
	 <p class="loadTxt"><%=cause_funds_percentage_completed cause %> of <%= number_to_currency cause.funds_needed, :precision => 0 %></p>
   </div>
</div>

app/views/home/_choose_period.html.erb
<% content_for(:js) do %>
  $(function() {
		setCustomPeriodWithoutSubmitting();
    $('#period').change(setCustomPeriod);
	});

  function setCustomPeriodWithoutSubmitting() {
    if ($('#period').attr('value') == "custom") {
        $('#custom_period').show();
    } else {
      $('#custom_period').hide();
    }
  }

  function setCustomPeriod() {
    if ($('#period').attr('value') == "custom") {
        $('#custom_period').show();
    } else {
      $('#custom_period').hide();
      $('#form').submit();
    }
  }

  function validateDate() {
    dateFrom = new Date(
      parseInt($('#custom_from_year').val()),
      parseInt($('#custom_from_month').val()) - 1,
      parseInt($('#custom_from_day').val())
    );

    dateTo = new Date(
      parseInt($('#custom_to_year').val()),
      parseInt($('#custom_to_month').val()) - 1,
      parseInt($('#custom_to_day').val())
    );

    if (dateFrom > dateTo) {
      $('.error').html('<p><%=escape_javascript _("Date from can't be bigger than date to") %></p>');
      return false;
    } else {
      return true;
    }

    
  }
<% end %>

<%= form_tag(request.path, :method => "get",:id => "form", :onsubmit => "return validateDate();") do %>
  <%= select_tag :period, options_for_select(@periods, @period),:class=>"genChoo dashChoo" %>
  <div id="custom_period" class = "nodisplay">
    <br/>
    <br/>
    <p class = "cloud3">
      <%= _('From:') %>
      <%= select_date @from, {:prefix => 'custom_from', :start_year => 2000, :end_year => 2020},:class => "date_select" %>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <%= _('To:') %>
      <%= select_date @to,{:prefix => 'custom_to', :start_year => 2000, :end_year => 2020},:class => "date_select"%>
    </p>
    <div class="buttonMainSearM">
      <div class="buttonSide accBtnSt"></div>
  	  <%= submit_tag _('Search'), :class => "buttonMid accBtnMi" %>
      <div class="buttonSide accBtnEn"></div><br class="spacer" />
    </div>
    <br />
    <div class="error"></div>
  </div>
<% end %>

app/views/home/_eula.html.erb
<%= _("This is about you and your rights.") %>

app/views/home/_user_nav.html.erb
<% content_for(:js) do %>
  $(function() {
    $('#language').change(function() {
      $('#nav_form').submit();
    });
	});
<% end %>

<div id="user_nav">
  <%= form_tag(change_language_path, :method => "get", :id => "nav_form") do %>
    <% if user_signed_in? %>
      <%= _("Signed in as") %> <%= current_user.email %>. <%= link_to _("Not you?"), destroy_user_session_path %> |
          <% if (current_user.type == "Charity") %>
            <%= link_to _("Charity Settings"), edit_user_registration_path %>
          <% elsif (current_user.type == "PersonalUser") %>
            <%= link_to _("User Settings"), edit_user_registration_path %>
          <% elsif (current_user.type == "Admin") %>
            <%= link_to _("Admin Tools"), admin_tools_path %>
          <% end %>
    <% else %>
      <%= link_to _("Sign up"), new_user_registration_path %>  (<%= link_to _("Forgot your password?"), new_user_password_path %>) |
      <%= link_to _("Sign in via bivo"), new_user_session_path %> |
      <%= link_to _("Sign in via facebook"), "/auth/facebook", :confirm => _("If you are a charity, please use bivo registration and cancel the sign in. Otherwise, click ok.") %>
    <% end %>
    | <%= _('Language:') %>
    <%= select_tag :language, options_for_select(languages.collect { |l| [l.name, l.id] }, language.id ) %>
  <% end %>
</div>

app/views/home/about.html.erb
<div class="inbodyM">
	<div class="bodyInner">

<div class="bodyInL">
	<div class="bodyInLTop"><span></span></div>
	<div class="bodyInLmid">
		<div class="bodyInLmidIn">
			<h2>About Bivo</h2>
			<ul>
				<li><%= link_to_static_page :who_we_are        %></li>
				<li><%= link_to_static_page :how_it_works      %></li>
				<li><%= link_to_static_page :faq               %></li>
				<li><%= link_to_static_page :our_team          %></li>
		        <li><%= link_to _("Charities We Help"), charities_url %></li>
				<li><%= link_to _("Shops"), all_shops_path %></li>
		        <li><%= link_to _("Statistics"), stats_path %></li>
				<li><%= link_to_static_page :contact_us        %></li>
			</ul>
			<h2>Bivo Ideas</h2>
			<ul>
				<li><%= link_to_static_page :fund_raisers      %></li>
				<li><%= link_to_static_page :social_initiatives%></li>
			</ul>
			<h2>Help Bivo</h2>
			<ul>
				<li><%= link_to_static_page :spread_the_word   %></li>
				<li><%= link_to_static_page :volunteer         %></li>
				<li><%= link_to _("Send Feedback"), feedback_url %></li>
			</ul>
         </div>
    </div>
	<div class="bodyInLbot"></div>
</div>

<div class="bodyInR">
	<h2><%= static_page_title @id %></h2>
	
	<div class="bodyInRBox"><div class="bodyInRBox2" id="static_page_content">
		<%= render :partial => "static_pages/#{@id}-#{I18n.locale}" %>
	</div></div>
</div>

	</div>
	
	<div class="bodyBot"></div>
</div>

app/views/home/accept_eula.html.erb
<%= large_single_block _('Terms and conditions') do %>

<p class="default_font">
<%= _("As you login from facebook the first time, you should accept the terms and conditions of Bivo") %>
</p>

<div class="default_font">
  <%= render :partial => "static_pages/eula-#{I18n.locale}" %>
</div>

<br/>
<div>
<%= form_tag confirm_eula_path do %>
  <p><%= check_box_tag :eula_accepted %>
  <%= label_tag :eula_accepted, _("I agree to the terms and conditions"), :class => 'default_font' %></p>
  <div class="buttons">
  <%= orange_submit_tag _("Accept") %>
  </div>
<% end %>
</div>

<% end %>

app/views/home/dashboard.html.erb
<div class="inbodyM">
	<div class="bodyInner">
    	<div class="statGrT"><h2><%=_("Dashboard")%></h2></div>
        <div class="boxMain">


        <%= render 'choose_period' %>

            <br class="spacer" />

            <div class="dashBoxL">

            	<div class="dashBoxLBox"><span class="dashBoxLNo"><%= number_to_currency(@funds_raised,:precision => 0) %></span><span class="dashBoxLTxt"><%=_("funds raised")%></span></div>

               <div class="dashBoxLBox"><span class="dashBoxLNo"><%=number_with_delimiter  @transactions %></span><span class="dashBoxLTxt"><%=_("transactions")%></span></div>
               <div class="dashBoxLBox"><span class="dashBoxLNo"><%=number_with_delimiter  @fully_funded_causes %></span><span class="dashBoxLTxt"><%=_("fully funded causes")%></span></div>
            </div>

        	<div class="dashBoxR">
	
				<div class="dashBoxRin">
				  <h3><%=_("Causes currently raising funds")%></h3>
				  <% if @causes_raising_funds.empty? %><p class="clickTxt"><%= _("No causes to display") %></p><% end %>
				  <div class="boxRIn">
				    <% @causes_raising_funds.each do |cause| %>
						<%= render :partial => 'cause_card', :locals => { :cause => cause } %>
				    <% end %>
				    <br class="spacer" />
				  </div>
				</div>
	
            	<div class="dashBoxRin">
                	<h3><%= _("Fundraising Sources") %></h3>
                    <div class="cloud">

  <% @shops_to_cloud.each do |shop| %>
    <%= link_to(shop.display_name, shop_path(shop.id), :style => "font-size:#{shop.font_size}px;") %>
  <% end %>
           <br class="spacer" />

                    </div>
                </div>



                <div class="dashBoxRin">
                  <h3><%=_("Causes funded")%></h3>
                  <% if @causes_being_funded.empty? %><p class="clickTxt"><%= _("No causes in the current period") %></p><% end %>
                  <div class="boxRIn">
                    <% @causes_being_funded.each do |cause| %>
						<%= render :partial => 'cause_card', :locals => { :cause => cause } %>
                    <% end %>
                    <br class="spacer" />
                  </div>
                </div>


                <div class="dashBoxRin">
                	<h3><%=_("Most voted causes queued for funding")%></h3>
                  <% if @most_voted_causes.empty? %><p class="clickTxt"><%= _("No causes in the current period") %></p><% end %>

                  <div class="boxRIn">

                  <% @most_voted_causes.each do |cause| %>
                      <div class="boxHu">
                        	<h3><%=cause.cause_category.name%></h3>
                            <p class="boxHuTxt boxHuTxt2"><%= link_to_cause cause %></p>

                            <p class="ghanaTxt"><%= number_to_currency(cause.funds_needed,:precision => 0)%></p>
                            <p class="ghanaTxt2"><%=_("to be raised")%></p>
                        </div>
                    <%end%>
                    <br class="spacer" />
                    </div>
                </div>

            </div><br class="spacer" />

        </div>

     </div>
	 <div class="bodyBot"></div>
</div>

app/views/home/eula.html.erb
<%= large_single_block _('Terms and conditions') do %>

<div class="default_font">
  <%= render :partial => "static_pages/eula-#{I18n.locale}" %>
</div>

<% end %>

app/views/home/index.html.erb
<% content_for :home_content do %>
<div class="banM">
  <div class="banMIN">
    <div class="banL">
        <h2 class="banWhHead"><%=_("Search For Products or Services") %></h2>
        <p><%=_("Search for a product, service, or retailer, such as Amazon, here.") %></p>
        <p><%=_("When you buy from any of Bivo's participating sellers, you support causes that make a difference in the world.") %></p>
        <p><%=_("You get the same great deal, and deserving charitable efforts get the funding they need.") %></p>
        <%= form_tag(shop_search_path, :method => :get) do %>
          <%= text_field_tag :search_word, nil, :class => 'banLFill' %>
          <div class="buttonMainLog goBtnMain">
            <div class="logBtnSt"></div>
            <%= submit_tag _("GO"), :class => "buttonMidlog" %>
            <div class="logBtnEn"></div><br class="spacer" />
          </div>
        <% end -%>
        <br class="spacer" />
    </div>
		  
    <div class="banR">
      <h2 class="banWhHead">
        <%=_("Creating a better world.")%><br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%=_("One purchase at a time.")%>
      </h2>
      <p>
        <%= _("Buy products and services using Bivo. Participating sellers give a portion of your purchase price to Bivo, which we use to support the causes you vote for.") %>
      </p>
      <p class="banRDolarTxt"><%= number_to_currency(@raised_amount,:precision => 0) %></p>
      <p><%= _("Using Bivo to buy online costs you nothing, but it can mean everything to those who need your help today.") %></p>
      <div class="buttonMainSee1">
        <div class="see1BtnSt"></div>
        <%= link_to _("See How it Works !"), static_page(:how_it_works), :class => "buttonMidSee1" %>
        <div class="see1BtnEn"></div><br class="spacer" />
      </div>
    </div>
    <br class="spacer" />
  </div>
</div>
<%end%>

<%= render :partial => "/shared/pre_footer" %>

app/views/home/stats.html.erb
<div class="inbodyM">
	<div class="bodyInner">
    	<div class="statGrT"><h2>Statistics</h2></div>
        <div class="boxMain">
			<%= render 'choose_period' %>
			<br class="spacer" />
            <div class="statIn">
            	<h3 class="statGrTop"><%= _("Overall performance") %></h3>
                <ul class="statInmain">
                	<li class="statInBox"><span class="statInBoxNo"><%= number_to_currency @revenues_total %></span><span class="statInBoxTxt"><%= _("revenue") %></span></li>
                    <li class="statInBox"><span class="statInBoxNo"><%= number_to_currency @expenses_total %></span><span class="statInBoxTxt"><%= _("expenses") %></span></li>
                    <li class="statInBox noMarg"><span class="statInBoxNo"><%= number_to_currency @cash_reserves %></span><span class="statInBoxTxt"><%= _("cash reserves") %></span></li><br class="spacer" />
                </ul>
                <div class="statInL">
                	<h3 class="statGrTop"><%= _("Expenses") %></h3>
                    <div class="statIn2main">
						<% for cat in @expense_categories %>
                        <ul class="inTab">
                        	<li class="inTabL"><%= cat.name %></li>
                            <li class="inTabR"><%= number_to_currency cat.amount %></li><br class="spacer" />
                        </ul>
						<% end %>
                        <ul class="inTab inTab2">
                        	<li class="inTabL"><%= _("Total Expenses")%></li>
                            <li class="inTabR"><%= number_to_currency @expenses_total %></li><br class="spacer" />
                        </ul>
                    </div>
                </div>
                <div class="statInR">
                	<h3 class="statGrTop"><%= _("Revenue") %></h3>
                    <div class="statIn2main">
					  <% for cat in @revenue_categories %>
                      <ul class="inTab">
						<li class="inTabL"><%= cat.name %></li>
                    	<li class="inTabR"><%= number_to_currency cat.revenue_amount %></li><br class="spacer" />
                      </ul>
					  <% end %>	
                        <ul class="inTab inTab2">
                        	<li class="inTabL"><%= _("Total Revenue")%></li>
                            <li class="inTabR"><%= number_to_currency @revenues_total %></li><br class="spacer" />
                        </ul>
                    </div>
                </div><br class="spacer" />
                <h3 class="statGrTop"><%= _("Expenses details") %></h3>
                <div class="statInmainBord" id="masterdiv">
                  <table class="zebra_table">
                    <tr>
                      <th style="width:100px;"><%= _("Type") %></th>
                      <th style="width:450px;"><%= _("Description") %></th>
                      <th style="width:200px;"><%= _("Paid to") %></th>
                      <th class="noBord" style="width:150px;"><%= _("Amount") %></th>
                    </tr>
                    <% @expenses.each_with_index do |expense, index| %>
                      <tr>
                        <td><%= expense.expense_category.name rescue nil %></td>
                        <td><%= expense.description %></td>
                        <td><%= expense.paid_to %></td>
                        <td class="noBord"><%= number_to_currency expense.amount %></td>
                      </tr>
                    <% end %>
                  </table>                    
                </div>
			</div>

            <h3 class="statGrTop"><%= _("Revenue details") %></h3>
            <div class="statInmainBord" id="masterdiv">
              <table class="zebra_table">
                <tr>
                  <th style="width:100px;"><%=_('Type')%></th>
                  <th style="width:650px;"><%=_('Channel')%></th>
                  <th class="noBord" style="width:150px;"><%=_('Amount')%></th>
                </tr>
                <% @revenues.each_with_index do |revenue, index| %>
                  <tr>
                    <td><%= revenue.income_category.name rescue nil %></td>
                    <td><%= revenue.detail %></td>
                    <td class="noBord"><%= number_to_currency revenue.revenue_amount %></td>
                  </tr>
                <% end %>
              </table>
            </div>
            <p class="statBotTxt">If you can help us optimize our expenses please <%=link_to _("contact us"), static_page(:contact_us) %> or post your proposal to the <%= link_to _("community forum"), feedback_url %></a>.</p> 
		</div>
	</div>
</div>