config/routes.rb
Bivo::Application.routes.draw do

  constraints(ShopSubdomain) do
    get "/all", :controller => "shops", :action => "index"
    get ":short_url", :controller => "shops", :action => "home", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
    get ":short_url/details", :controller => "shops", :action => "details", :constraints => { :short_url => Shop::UrlFormat, :subdomain => /shop/ }
  end

  devise_for :users, :controllers => {:registrations => 'registrations' }
  match '/auth/facebook/callback' => 'facebook_authentications#create'

  #news
  post "news/:id/destroy", :to => "news#destroy"

  #gallery
  get "gallery/:entity_type/:entity_id/edit", :to => "galleries#edit", :as=>"edit_gallery"
  post "gallery/:entity_type/:entity_id/:id/move_up", :to => "galleries#move_up"
  post "gallery/:entity_type/:entity_id/:id/move_down", :to => "galleries#move_down"
  post "gallery/:entity_type/:entity_id/:id/remove_item", :to => "galleries#remove_item"
  post "gallery/:entity_type/:entity_id/add_photo", :to => "galleries#add_photo"
  post "gallery/:entity_type/:entity_id/add_video", :to => "galleries#add_video"

  #comments
  post "comments/:id/destroy", :to => "comments#destroy"
  get "comments/:id/edit", :to => "comments#edit"
  post "comments/:id/update", :to => "comments#update"
  post "comments/:id/approve", :to => "comments#approve"
  post "comments/create", :to => "comments#create"

  #incomes and expenses
  resources :expense_categories
  get "expense/list_categories", :to => "expense_categories#list_options"

  resources :income_categories
  get "income/list_categories", :to => "income_categories#list_options"

#incomes categories
  #post "income_categories/create", :to => "income_categories#create"
  #put "income_categories/update/:id", :to => "income_categories#update"
  #delete "income_categories/:id", :to => "income_categories#destroy"

  #paths for admin manager
  get "admin/send_mails"
  get "admin/tools"
  get "admin/user_manager", :as => "admin_user_manager"
  get "admin/new_personal_user", :to => "admin#new_personal_user", :as => "admin_new_personal_user"
  post "admin/create_personal_user", :to => "admin#create_personal_user", :as => "admin_create_personal_user"
  get "admin/new_charity", :to => "admin#new_charity", :as => "admin_new_charity"
  post "admin/create_charity", :to => "admin#create_charity", :as => "admin_create_charity"

  post "admin/delete_user/:id", :to => "admin#delete_user", :as => "admin_delete_user"

  get 'admin/shop/categories', :to => 'shop_categories#edit', :as => 'admin_edit_shop_categories'
  post 'admin/shop/categories/create', :to => 'shop_categories#create'
  match 'admin/shop/categories/update', :to => 'shop_categories#update'
  match 'admin/shop/categories/delete', :to => 'shop_categories#destroy'

  get 'admin/language', :to => "admin#choose_language", :as => 'translation'
  get 'admin/translate', :to => "admin#translate"

  post 'admin/save_translation', :to => "admin#save_translation"

  #paths for handling eula
  get "eula", :to => "home#eula", :as => "eula"
  get "accept_eula",  :to => "home#accept_eula", :as => "accept_eula"
  post "confirm_eula", :to => "home#confirm_eula", :as => "confirm_eula"

  #paths for dashboard
  get "dashboard", :to => "home#dashboard", :as => "dashboard"
  get "stats", :to => "home#stats", :as => "stats"

  #paths for charities
  get "charity/a/check_url", :to => "charities#check_url"

  resources :charities, :path => 'charity/a' do
    member do
      get  :manage_comments
      post :activate
      post :deactivate
      post :follow
      post :unfollow
    end
    resources :news
  end

  get "charity/:url", :controller => "charities", :action => "details", :constraints => { :url => Charity::UrlFormat }

  get "shop/a/search/", :controller => "shops", :as => "shop_search", :action => "search"

  resources :shops, :path => 'shop/a' do
    member do
      post :activate
      post :deactivate
    end
    collection do
      get :edit_categories
    end
  end

  get "cause/a/check_url", :controller => "causes", :action => "check_url", :as => 'check_cause_url'

  resources :causes, :path => 'cause/a' do
    member do
      post :activate
      post :deactivate
      post :mark_paid
      post :mark_unpaid
      post :vote
      post :follow
      post :unfollow
    end

    resources :news
  end

  get "cause/:url", :controller => "causes", :action => "details", :as => "cause_details", :constraints => { :url => Cause::UrlFormat }

  post "transaction/:id", :controller => "transactions", :action => "update",:as => "transaction_update"
  delete "transaction/:id",:controller => "transactions", :action => "destroy",:as => "transaction_destroy"
  get "transaction/:id/edit", :controller => "transactions", :action => "edit", :as => "transaction_edit"

  get "transaction", :controller => "transactions", :action => "index", :as => 'transaction_list'

  resources :transactions, :path => 'transaction', :except => :destroy

  post "change_language", :to => "home#change_language"
  post "change_currency", :to => "home#change_currency"

  # path for static pages
  get "about(/:id)", :to => "home#about"
  get "about/:locale/:id", :to => "home#about"

  root :to => "home#index"

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  before_filter :only_admin, :except => [:index]

 def index


    if params[:kind]
      @sorting = params[:sorting].to_sym
    else
      @sorting = :all
    end

   # Filter by kind (income-expense)
    if params[:kind]
      @kind = params[:kind].to_sym
    else
      @kind = :all
    end

    # Filter by description
    if params[:description]
      @description = params[:description]
    else
      @description = ""
    end

    load_periods

    # get transactions by kind
    if @kind && @kind == :all
      @transactions = Transaction.where("transactions.type ~* 'Expense' OR transactions.type ~* 'Income'")
    else
      @transactions = Transaction.where("transactions.type ~* ?",@kind)
    end

    #get transactions that match description
    @transactions = @transactions.where("transactions.description ~* ?", @description) unless @description.blank?

    #get transactions that match period
    @transactions = @transactions.where('transactions.transaction_date BETWEEN ? AND ?', @from, @to) unless @period.nil?

    @transactions = @transactions.order case @sorting
      when :type then 'type ASC'
      when :date_new then 'transaction_date DESC'
      when :date_old then 'transaction_date ASC'
      when :description then 'description ASC'
      when :amount_desc then 'amount DESC'
      when :amount_asc then 'amount ASC'

      else'id ASC'
     end

    # Set result count
    @count = @transactions.count

    # Set pagination
    @sortings = [
      [_('type'), :type],
      [_('newest'), :date_new],
      [_('oldest'), :date_old],
      [_('description'), :description],
      [_('greater amount'),:amount_desc],
      [_('lower amount'),:amount_asc]
    ]
    @per_page = (params[:per_page] || 10).to_i
    @transactions = @transactions.paginate(:per_page => @per_page, :page => params[:page])
    @kinds = [:all, :income, :expense]

    @page_sizes = [5,10,20,50,100]

  end

  def new
    load_create_options
    @transaction = Transaction.new
  end

  def create
    type = params["transaction"].delete("type")

    if (type == "Income")
      @transaction = Income.new(params["transaction"])
    elsif (type == "Expense")
      @transaction = Expense.new(params["transaction"])
    else
      @transaction = Transaction.new
    end

    @transaction.user = current_user

    if (@transaction.save)
      redirect_to transaction_list_path
    else
      load_create_options
      render "new"
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
    load_update_options
  end

  def update
    @transaction = Transaction.find(params[:id])
    @transaction.description = params[:transaction][:description]
    @transaction.input_currency = params["transaction"]["input_currency"]
    @transaction.input_amount = params["transaction"]["amount"]

    if @transaction.save
      redirect_to transaction_list_path
    else
      load_update_options

      render "edit"
    end
  end

  private

  def load_create_options
    load_currency
    @currencies = Currency.all.collect { |c| [c.name, c.id] }
    @income_categories = IncomeCategory.all
    @expense_categories = ExpenseCategory.all
    @shops = Shop.all
  end

  def load_update_options
    load_currency
    @currencies = Currency.all.collect { |c| [c.name, c.id] }
  end

  def load_currency
    if (params["transaction"])
      @currency = params["transaction"]["input_currency"]
    else
      @currency = Transaction::DefaultCurrency
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def edit_transaction_title_for(type)
    if (type == "Income")
      _("Edit Income")
    elsif (type == "Expense")
      _("Edit Expense")
    end
  end

  def transactions_category_name(transaction)
    if (transaction.type == "Income")
      transaction.income_category.name rescue nil
    else
      transaction.expense_category.name rescue nil
    end
  end
end

app/views/transactions/_expense_fields.html.erb
    <%= f.label :category %>
    <%= f.select :expense_category_id, expense_categories.collect{ |c| [c.name, c.id] }, :include_blank => true %>

	<p class="accfilTxt" style="width: 100%; padding-left: 175px;">
		<%= link_to _("Manage Categories"), expense_categories_path, :class => "iframe" %>
	</p>
    
    <%= f.label :paid_to %>
    <%= f.text_field :paid_to %>

app/views/transactions/_income_fields.html.erb
   <%= f.label :sources %>
   <%= f.select :income_category_id, income_categories.collect{ |c| [c.name, c.id] }, :include_blank => true %>

	<p class="accfilTxt" style="width: 100%; padding-left: 175px;">
		<%= link_to _("Manage Sources"), income_categories_path, :class => "iframe" %>
	</p>

    <div id="shop" style="<%= get_shop_display(transaction) %>">
      <%= f.label :shops %>
      <%= f.select :shop_id, shops.collect{ |s| [s.name, s.id] }, :include_blank => true %>
    </div>

app/views/transactions/_transactions.html.erb
<table class="zebra_table">
  <tr>
    <th style="width:80px;"><%=_("Type")%></th>
    <th style="width:90px;"><%=_("Date")%></th>
    <th style="width:455px;"><%=_("Description")%></th>
    <th style="width:100px;"><%=_("Category")%></th>
    <th style="width:90px;"><%=_("Detail")%></th>
    <th style="width:60px;"><%=_("Amount")%></th>
    <th class="noBord" style="width:80px;">&nbsp;</th>
  </tr>
  <% for transaction in @transactions %>
    <tr>
      <td><%= transaction.type %></td>
      <td><%= transaction.transaction_date %></td>
      <td><%= transaction.description %></td>
      <td><%=transactions_category_name(transaction) %></td>
      <td><%= transaction.detail %></td>
      <td><%= number_to_currency(transaction.amount,:precision => 0) %></td>
      <td class="noBord"><%= orange_link_to _("Edit"),transaction_edit_path(transaction.id)%></td>
    </tr>
  <% end %>
</table>

app/views/transactions/edit.html.erb
<% content_for :js do %>
$(document).ready(function(){
  $('#cancel').click(function () {
    location.href = "<%= transaction_list_path %>";
    return false;
  })
});

<% end %>

<%= single_block (_("Transactions | ") + (edit_transaction_title_for @transaction.type)) do %>

  <%= bivo_form_for(@transaction, :as => :transaction, :url => transaction_update_path, :id => @transaction.id) do |f| %>
    <%= render "shared/error_messages", :target => @transaction %>

    <%= f.label :amount %>
    <%= f.select :input_currency, @currencies, :selected => @currency %>
    <%= f.label ' ' %>
    <%= f.text_field :amount %>

    <%= f.label :description %>
    <%= f.text_area :description %>

	<div class="buttons">
    	<%= f.submit :Save %> <%=back_button(_("Cancel"))%>
	</div>
  <% end %>

<% end %>

app/views/transactions/edit_transaction.html.erb
<% content_for :js do %>
$(document).ready(function(){
  $('#cancel').click(function () {
    location.href = "<%= transaction_list_path %>";
    return false;
  })
});

<% end %>

<h2>

  <% if (@transaction.type == "Income") %>
    <%= _("Edit Income") %>
  <% else %>
    <%= _("Edit Expense") %>
  <% end %>


</h2>


<%= form_for(@transaction, :as => :transaction, :url => transaction_update_path, :id => @transaction.id) do |f| %>
  <%= render "shared/error_messages", :target => @transaction %>

  <div class="field">
    <%= f.label :amount %><br />
    <%= select_tag :currency, options_for_select(@currencies, @currency) %>
    <%= f.text_field :amount %></p>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <p><%= f.submit :Save %> <%= f.submit :Cancel, :id => "cancel" %></p>
<% end %>

app/views/transactions/index.html.erb
<% content_for(:head) do %>
	<%#= javascript_include_tag "pagination" %>
<% end %>

<% content_for(:js) do %>
  $(function() {
		showOrHiddenCustomPeriod();
    $('#period').change(showOrHiddenCustomPeriod);
	});

  function showOrHiddenCustomPeriod(){
    if ($('#period').attr('value') == "custom")
      {
        $('#custom').show();
      }
      else{
        $('#custom').hide();
      }
    }
<% end %>

<%= title _("Transactions") %>

<%= large_single_block _("Transactions") do %>
  <%=raw @info%>

  <br class="spacer" />

  <%= orange_link_to _("add transaction"), new_transaction_path%>

  <br class="spacer" />
  <br class="spacer" />
  <%= form_tag transactions_path, :method => :get, :id => "filter_form" do %>
    <div class="container">
      <div id="gnFilMain2">
        <p class="genFilTxt2">
        	<%= _('Show') %>
	        <%= select_tag :kind, options_for_select(@kinds, @kind), :class => :genChoo2 %>
        </p>

        <p class="genFilTxt2">
          <%= _('Order By') %>
	        <%= select_tag :sorting, options_for_select(@sortings, @sorting), :class => :genChoo2 %>
        </p>


         <p class="genFilTxt2"><%= _('Filter by') %></p>
        <p>
          <%= text_field_tag :description, @description, :id => 'description_filter', :class => "genFil" %>
          <%= link_to_function(_('clear'), "$('#description_filter').val('').change();") if @name %>
        </p>
        <p class="genFilTxt2">
          <%= _('Period') %>
	        <%= select_tag :period, options_for_select(@periods, @period), :class => :genChoo2 %>
        </p>
        <div id="custom">
          <br class="spacer"/> <br class="spacer"/>
          <p class="genFilTxt2">
            <%= _('From') %>
            <%= select_date @from, :prefix => :custom_from, :start_year => 2000, :end_year => 2020, :class => :genChoo2 %>
          </p>
          <p class="genFilTxt2">
            <%= _('To') %>
            <%= select_date @to, :prefix => :custom_to,:start_year => 2000, :end_year => 2020, :class => :genChoo2 %>
          </p>
        </div>
        <br class="spacer"/>
        <br class="spacer"/>
       	<div style="margin-left:430px;"><%= orange_submit_tag _('Search'), :disable_with => _('Searching...') %></div>
      </div>

      <br class="spacer">

		  <div class="gnFilMain">
      	<h3 class="shopRinHead searInHead">
          <%= n_("%{count} Result Found", "%{count} Results Found", @count) % {:count => @count} %>
        </h3>
          <div class="pegi pagination"><%= styled_will_paginate @transactions %></div>
          <br class="spacer" />
      </div>

      <div id="transactions">
        <%= render 'transactions' %>
        <br class="spacer" />
        <%= select_tag :per_page, options_from_collection_for_select(@page_sizes, 'to_i', 'to_s', @per_page), :class => :showChoo, :onchange => submit_form %>
        <p class="showTxt"><%= _("Show per page")%></p>
        <br />
      </div>
    </div>
  <% end %>
<% end %>

app/views/transactions/index.js.erb
$("#transactions").html("<%= escape_javascript(render("transactions")) %>");
<%= render(:partial => 'shared/notifications.js') %>

app/views/transactions/new.html.erb
<% content_for :js do %>

$(document).ready(function(){
  $("a.iframe").fancybox({
    'onClosed': function() {

		  // save current selection
		  var current_selection = $('#transaction_expense_category_id').val();
      var income_current_selection = $('#transaction_income_category_id').val();

		  $('#transaction_expense_category_id')
		  .load('<%=url_for :controller => 'expense_categories', :action => 'list_options'%>', function(){
        if (current_selection) {
          $("#transaction_expense_category_id option[value='" + current_selection + "']").attr('selected', 'selected');
        }
		  });

      $('#transaction_income_category_id')
		  .load('<%=url_for :controller => 'income_categories', :action => 'list_options'%>', function(){
        if (income_current_selection) {
          $("#transaction_income_category_id option[value='" + income_current_selection + "']").attr('selected', 'selected');
        }
		  });
    }
  });

  $('#transaction_income_category_id').change(function() {
    var selectedCategory = $('#transaction_income_category_id :selected').text();
    if (selectedCategory == "shop") {
      $("#shop").css("display", "inline");
    } else {
      $("#shop").css("display", "none");
    }
  });

  $('#transaction_type').change(function() {
    var selectedCategory = $('#transaction_type :selected').text();
    if (selectedCategory == "Income") {
      $("#income_fields").css("display", "inline");
      $("#expense_fields").css("display", "none");
    } else if (selectedCategory == "Expense") {
      $("#income_fields").css("display", "none");
      $("#expense_fields").css("display", "inline");
    } else {
      $("#income_fields").css("display", "none");
      $("#expense_fields").css("display", "none");
    }
  });

  $('#cancel').click(function () {
    location.href = "<%= root_path %>";
    return false;
  })
});

<% end %>

<%= single_block _("Transactions | Add Income/Expense") do %>

<%= bivo_form_for(@transaction, :as => :transaction, :url => {:controller => "transactions", :action => "create"}) do |f| %>
  <%= render "shared/error_messages", :target => @transaction %>

  <%= f.label :type %>
  <%= f.select :type, [["Income","Income"], ["Expense","Expense"]], :include_blank => true %>

  <%= f.label :date %>
  <%= f.date_select :transaction_date %>
  <br class="spacer"/>

  <div id="income_fields" style="<%= get_display_of :Income, @transaction %>">
    <%= render :partial => "income_fields",
          :locals => {:f => f, :income_categories => @income_categories, :shops => @shops, :transaction => @transaction} %>
  </div>

  <div id="expense_fields" style="<%= get_display_of :Expense, @transaction %>">
    <%= render :partial => "expense_fields",
          :locals => {:f => f, :expense_categories => @expense_categories} %>
  </div>

  <%= f.label :amount %>
  <%= f.select :input_currency, @currencies, :selected => @currency %>
  <%= f.label ' ' %>
  <%= f.text_field :input_amount %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <div class="buttons">
  	<%= f.submit :Save %> <%= f.submit :Cancel, :id => "cancel" %>
  </div>
<% end %>

<% end %>